import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    // ... existing EN translations
    home: 'Home',
    courses: 'Courses',
    login: 'Login',
    register: 'Register',
    dashboard: 'Dashboard',
    profile: 'Profile',
    admin: 'Admin',
    logout: 'Logout',
    welcomeTitle: 'Welcome to Learning Platform',
    welcomeSubtitle: 'Master new skills with interactive courses, quizzes, and certificates',
    aboutMe: 'About Me',
    aboutDescription: 'We are dedicated to providing high-quality online education with interactive learning experiences.',
    getStarted: 'Get Started',
    learnMore: 'Learn More',
    allCourses: 'All Courses',
    courseDetails: 'Course Details',
    startCourse: 'Start Course',
    duration: 'Duration',
    benefits: 'Benefits',
    downloadPDF: 'Download PDF',
    quiz: 'Quiz',
    question: 'Question',
    timeRemaining: 'Time Remaining',
    nextQuestion: 'Next Question',
    finishQuiz: 'Finish Quiz',
    quizCompleted: 'Quiz Completed!',
    yourScore: 'Your Score',
    watchVideo: 'Watch Video',
    continue: 'Continue',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    fullName: 'Full Name',
    loginTitle: 'Login to Your Account',
    registerTitle: 'Create New Account',
    alreadyHaveAccount: 'Already have an account?',
    dontHaveAccount: "Don't have an account?",
    adminDashboard: 'Admin Dashboard',
    createCourse: 'Create Course',
    manageCourses: 'Manage Courses',
    createQuiz: 'Create Quiz',
    uploadPDF: 'Upload PDF',
    uploadVideo: 'Upload Video',
    courseTitle: 'Course Title',
    courseDescription: 'Course Description',
    courseBenefits: 'Course Benefits',
    back: 'Back',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    upload: 'Upload',
    download: 'Download',
    loading: 'Loading...',
    success: 'Success!',
    error: 'Error!',
    notImplemented: '🚧 This feature isn\'t implemented yet—but don\'t worry! You can request it in your next prompt! 🚀',
    
    // New Translations
    myCertificates: "My Certificates",
    generateCertificate: "Generate Certificate",
    finalExam: "Final Exam",
    startExam: "Start Exam",
    examScore: "Exam Score",
    points: "Points",
    congratulations: "Congratulations!",
    youPassedTheExam: "You have successfully passed the exam and earned a certificate!",
    viewCertificate: "View Certificate",
    failedExam: "Try Again",
    youFailedTheExam: "Unfortunately, you did not pass the exam. Please review the material and try again.",
    retakeExam: "Retake Exam",
    referralSystem: "Referral System",
    copyLink: "Copy Link",
    copied: "Copied!",
    referralInfo: "Share this link with your friends. You both get 10 points when they register!",
    discussionGroup: "Discussion Group",
    joinCommunity: "Join Community",
    yourPoints: "Your Points",
    manageExams: "Manage Exams",
    createExam: "Create Exam",
    examTitle: "Exam Title"
  },
  id: {
    // ... existing ID translations
    home: 'Beranda',
    courses: 'Kursus',
    login: 'Masuk',
    register: 'Daftar',
    dashboard: 'Dashboard',
    profile: 'Profil',
    admin: 'Admin',
    logout: 'Keluar',
    welcomeTitle: 'Selamat Datang di Platform Pembelajaran',
    welcomeSubtitle: 'Kuasai keterampilan baru dengan kursus interaktif, kuis, dan sertifikat',
    aboutMe: 'Tentang Kami',
    aboutDescription: 'Kami berdedikasi menyediakan pendidikan online berkualitas tinggi dengan pengalaman belajar interaktif.',
    getStarted: 'Mulai Sekarang',
    learnMore: 'Pelajari Lebih Lanjut',
    allCourses: 'Semua Kursus',
    courseDetails: 'Detail Kursus',
    startCourse: 'Mulai Kursus',
    duration: 'Durasi',
    benefits: 'Manfaat',
    downloadPDF: 'Unduh PDF',
    quiz: 'Kuis',
    question: 'Pertanyaan',
    timeRemaining: 'Waktu Tersisa',
    nextQuestion: 'Pertanyaan Selanjutnya',
    finishQuiz: 'Selesaikan Kuis',
    quizCompleted: 'Kuis Selesai!',
    yourScore: 'Skor Anda',
    watchVideo: 'Tonton Video',
    continue: 'Lanjutkan',
    email: 'Email',
    password: 'Kata Sandi',
    confirmPassword: 'Konfirmasi Kata Sandi',
    fullName: 'Nama Lengkap',
    loginTitle: 'Masuk ke Akun Anda',
    registerTitle: 'Buat Akun Baru',
    alreadyHaveAccount: 'Sudah punya akun?',
    dontHaveAccount: 'Belum punya akun?',
    adminDashboard: 'Dashboard Admin',
    createCourse: 'Buat Kursus',
    manageCourses: 'Kelola Kursus',
    createQuiz: 'Buat Kuis',
    uploadPDF: 'Upload PDF',
    uploadVideo: 'Upload Video',
    courseTitle: 'Judul Kursus',
    courseDescription: 'Deskripsi Kursus',
    courseBenefits: 'Manfaat Kursus',
    back: 'Kembali',
    save: 'Simpan',
    cancel: 'Batal',
    delete: 'Hapus',
    edit: 'Edit',
    upload: 'Upload',
    download: 'Unduh',
    loading: 'Memuat...',
    success: 'Berhasil!',
    error: 'Error!',
    notImplemented: '🚧 Fitur ini belum diimplementasikan—tapi jangan khawatir! Anda bisa memintanya di prompt berikutnya! 🚀',
    
    // New Translations
    myCertificates: "Sertifikat Saya",
    generateCertificate: "Buat Sertifikat",
    finalExam: "Ujian Akhir",
    startExam: "Mulai Ujian",
    examScore: "Skor Ujian",
    points: "Poin",
    congratulations: "Selamat!",
    youPassedTheExam: "Anda telah berhasil lulus ujian dan mendapatkan sertifikat!",
    viewCertificate: "Lihat Sertifikat",
    failedExam: "Coba Lagi",
    youFailedTheExam: "Sayangnya, Anda tidak lulus ujian. Harap tinjau kembali materi dan coba lagi.",
    retakeExam: "Ulangi Ujian",
    referralSystem: "Sistem Referral",
    copyLink: "Salin Tautan",
    copied: "Tersalin!",
    referralInfo: "Bagikan tautan ini dengan teman-teman Anda. Kalian berdua akan mendapatkan 10 poin saat mereka mendaftar!",
    discussionGroup: "Grup Diskusi",
    joinCommunity: "Gabung Komunitas",
    yourPoints: "Poin Anda",
    manageExams: "Kelola Ujian",
    createExam: "Buat Ujian",
    examTitle: "Judul Ujian"
  },
  ja: {
    // ... existing JA translations
    home: 'ホーム',
    courses: 'コース',
    login: 'ログイン',
    register: '登録',
    dashboard: 'ダッシュボード',
    profile: 'プロフィール',
    admin: '管理者',
    logout: 'ログアウト',
    welcomeTitle: '学習プラットフォームへようこそ',
    welcomeSubtitle: 'インタラクティブなコース、クイズ、証明書で新しいスキルをマスターしましょう',
    aboutMe: '私たちについて',
    aboutDescription: '私たちはインタラクティブな学習体験を通じて高品質なオンライン教育を提供することに専念しています。',
    getStarted: '始める',
    learnMore: '詳細を見る',
    allCourses: 'すべてのコース',
    courseDetails: 'コース詳細',
    startCourse: 'コースを開始',
    duration: '期間',
    benefits: 'メリット',
    downloadPDF: 'PDFダウンロード',
    quiz: 'クイズ',
    question: '質問',
    timeRemaining: '残り時間',
    nextQuestion: '次の質問',
    finishQuiz: 'クイズ終了',
    quizCompleted: 'クイズ完了！',
    yourScore: 'あなたのスコア',
    watchVideo: 'ビデオを見る',
    continue: '続ける',
    email: 'メール',
    password: 'パスワード',
    confirmPassword: 'パスワード確認',
    fullName: 'フルネーム',
    loginTitle: 'アカウントにログイン',
    registerTitle: '新しいアカウントを作成',
    alreadyHaveAccount: 'すでにアカウントをお持ちですか？',
    dontHaveAccount: 'アカウントをお持ちでないですか？',
    adminDashboard: '管理者ダッシュボード',
    createCourse: 'コース作成',
    manageCourses: 'コース管理',
    createQuiz: 'クイズ作成',
    uploadPDF: 'PDF アップロード',
    uploadVideo: 'ビデオアップロード',
    courseTitle: 'コースタイトル',
    courseDescription: 'コース説明',
    courseBenefits: 'コースのメリット',
    back: '戻る',
    save: '保存',
    cancel: 'キャンセル',
    delete: '削除',
    edit: '編集',
    upload: 'アップロード',
    download: 'ダウンロード',
    loading: '読み込み中...',
    success: '成功！',
    error: 'エラー！',
    notImplemented: '🚧 この機能はまだ実装されていません。次のプロンプトでリクエストしてください！ 🚀',
    
    // New Translations
    myCertificates: "私の証明書",
    generateCertificate: "証明書を生成",
    finalExam: "期末試験",
    startExam: "試験を開始",
    examScore: "試験スコア",
    points: "ポイント",
    congratulations: "おめでとう！",
    youPassedTheExam: "試験に合格し、証明書を獲得しました！",
    viewCertificate: "証明書を見る",
    failedExam: "再挑戦",
    youFailedTheExam: "残念ながら、試験に合格しませんでした。教材を見直して、再挑戦してください。",
    retakeExam: "試験を再受験",
    referralSystem: "紹介制度",
    copyLink: "リンクをコピー",
    copied: "コピーしました！",
    referralInfo: "このリンクを友達と共有してください。友達が登録すると、お互いに10ポイントもらえます！",
    discussionGroup: "ディスカッショングループ",
    joinCommunity: "コミュニティに参加",
    yourPoints: "あなたのポイント",
    manageExams: "試験を管理",
    createExam: "試験を作成",
    examTitle: "試験タイトル"
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('id');

  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};